name: CI -> Deploy to My website
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: cleanup
        run: rm -rf ".git" ".github" ".gitignore"
      # Here is the deployment action
      - name: Upload from public_html via FTP
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: 184.168.97.83
          user: developer@popularizers.in
          password: ${{ secrets.POPULARIZRS_DEV }}
          local_dir: "./dist"
          remote_dir: "./alpha"
